services:
    autome-web:
        container_name: autome-web
        image: nginx:alpine
        ports:
            - "9090:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - autome-app
        networks:
            - autome-network

    autome-app:
        container_name: autome-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - postgres
        volumes:
            - ./:/var/www
        networks:
            - autome-network

    postgres:
        image: postgres
        container_name: autome-postgres
        restart: always
        expose:
            - 5432
        ports:
            - "2345:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - autome_postgres_data:/var/lib/postgresql/data
        networks:
            - autome-network

    autome-pgadmin:
        image: dpage/pgadmin4
        container_name: autome-pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "8081:80"
        networks:
            - autome-network

    autome-node:
        image: node:20
        container_name: autome-node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - autome-network
        command: bash -c "npm install && npm run build && npm run dev"

networks:
    autome-network:
        driver: bridge

volumes:
    autome_postgres_data:
